// web/src/components/ProductCard.tsx
import { Link } from "react-router-dom";
import { Product } from "@/data/brands";

interface ProductCardProps {
  product: Product;
  brandColor: string;
}

const ProductCard = ({ product, brandColor }: ProductCardProps) => {
  return (
    <Link
      to={`/product/${product.id}`}
      className="product-card block overflow-hidden"
    >
      <div className="aspect-[4/3] overflow-hidden">
        <img
          src={product.image}
          alt={product.name}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          loading="lazy"
        />
      </div>
      <div className="p-3">
        <h4 className="font-medium text-foreground text-sm truncate">
          {product.name}
        </h4>
        {product.description && (
          <p className="text-muted-foreground text-xs mt-0.5 truncate">
            {product.description}
          </p>
        )}
      </div>
      {/* Hover accent line */}
      <div
        className="h-0.5 w-0 transition-all duration-300 group-hover:w-full"
        style={{ background: `hsl(${brandColor})` }}
      />
    </Link>
  );
};

export default ProductCard;

// web-angular/src/app/components/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Product } from '@/app/data/brands';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-product-card',
    standalone: true,
    imports: [RouterLink, CommonModule],
    templateUrl: './product-card.component.html',
})
export class ProductCardComponent {
    @Input({ required: true }) product!: Product;
    @Input({ required: true }) brandColor!: string;
}

<a [routerLink]="['/product', product.id]" class="product-card block overflow-hidden group h-full">
    <div class="aspect-[4/3] overflow-hidden">
        <img [src]="product.image" [alt]="product.name"
            class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" loading="lazy" />
    </div>
    <div class="p-3">
        <h4 class="font-medium text-foreground text-sm truncate">
            {{ product.name }}
        </h4>
        @if (product.description) {
        <p class="text-muted-foreground text-xs mt-0.5 truncate">
            {{ product.description }}
        </p>
        }
    </div>
    <!-- Hover accent line -->
    <div class="h-0.5 w-0 transition-all duration-300 group-hover:w-full"
        [style.background]="'hsl(' + brandColor + ')'"></div>
</a>
