// web-angular/src/app/components/navbar/navbar.component.ts
import { Component, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Menu, X } from 'lucide-angular';
import { ThemeToggleComponent } from '../theme-toggle/theme-toggle.component';
import { ButtonComponent } from '../ui/button/button.component';
import { cn } from '@/lib/utils';

@Component({
    selector: 'app-navbar',
    standalone: true,
    imports: [RouterLink, RouterLinkActive, CommonModule, LucideAngularModule, ThemeToggleComponent, ButtonComponent],
    templateUrl: './navbar.component.html',
})
export class NavbarComponent {
    mobileOpen = signal(false);
    readonly Menu = Menu;
    readonly X = X;

    navLinks = [
        { href: "/", label: "قاعة المعارض" },
        { href: "/about", label: "من نحن" },
        { href: "/contact", label: "تواصل معنا" },
    ];

    toggleMobile() {
        this.mobileOpen.update(v => !v);
    }

    closeMobile() {
        this.mobileOpen.set(false);
    }
}

<header class="fixed top-0 left-0 right-0 z-50 glass-panel border-b border-border/20">
    <nav class="container mx-auto px-4 h-16 flex items-center justify-between">
        <!-- Logo -->
        <a routerLink="/" class="flex items-center gap-3 group">
            <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                <span class="text-primary-foreground font-display font-bold text-lg">BZ</span>
            </div>
            <span class="font-display font-bold text-xl text-foreground group-hover:text-primary transition-colors">
                بازار زون
            </span>
        </a>

        <!-- Desktop Nav -->
        <div class="hidden md:flex items-center gap-8">
            <ng-container *ngFor="let link of navLinks">
                <!-- Using a regular anchor with routerLink and routerLinkActive -->
                <!-- Note: React version uses 'active' class when active. routerLinkActive applies class. -->
                <a [routerLink]="link.href" [routerLinkActive]="['active', 'text-foreground']"
                    [routerLinkActiveOptions]="{exact: true}" class="nav-link font-medium">
                    {{ link.label }}
                </a>
            </ng-container>
            <app-theme-toggle></app-theme-toggle>
            <button appButton variant="gold" size="sm">
                ابدأ الآن
            </button>
        </div>

        <!-- Mobile Menu Button -->
        <div class="md:hidden flex items-center gap-2">
            <app-theme-toggle></app-theme-toggle>
            <button class="text-foreground" (click)="toggleMobile()">
                <lucide-icon [name]="mobileOpen() ? X : Menu" class="w-6 h-6"></lucide-icon>
            </button>
        </div>
    </nav>

    <!-- Mobile Nav -->
    <div *ngIf="mobileOpen()" class="md:hidden glass-panel border-t border-border/20 animate-fade-in">
        <div class="container mx-auto px-4 py-4 flex flex-col gap-4">
            <ng-container *ngFor="let link of navLinks">
                <a [routerLink]="link.href" [routerLinkActive]="['text-primary']"
                    [routerLinkActiveOptions]="{exact: true}" (click)="closeMobile()"
                    class="text-foreground/70 hover:text-foreground font-medium py-2 transition-colors">
                    {{ link.label }}
                </a>
            </ng-container>
            <button appButton variant="gold" class="mt-2" w-full>
                ابدأ الآن
            </button>
        </div>
    </div>
</header>

// web/src/components/Navbar.tsx
import { Link, useLocation } from "react-router-dom";
import { useState } from "react";
import { Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import ThemeToggle from "@/components/ThemeToggle";

const navLinks = [
  { href: "/", label: "قاعة المعارض" },
  { href: "/about", label: "من نحن" },
  { href: "/contact", label: "تواصل معنا" },
];

const Navbar = () => {
  const location = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);

  return (
    <header className="fixed top-0 left-0 right-0 z-50 glass-panel border-b border-border/20">
      <nav className="container mx-auto px-4 h-16 flex items-center justify-between">
        {/* Logo */}
        <Link to="/" className="flex items-center gap-3 group">
          <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
            <span className="text-primary-foreground font-display font-bold text-lg">آد</span>
          </div>
          <span className="font-display font-bold text-xl text-foreground group-hover:text-primary transition-colors">
            آد إكسبو
          </span>
        </Link>

        {/* Desktop Nav */}
        <div className="hidden md:flex items-center gap-8">
          {navLinks.map((link) => (
            <Link
              key={link.href}
              to={link.href}
              className={cn(
                "nav-link font-medium",
                location.pathname === link.href && "active text-foreground"
              )}
            >
              {link.label}
            </Link>
          ))}
          <ThemeToggle />
          <Button variant="gold" size="sm">
            ابدأ الآن
          </Button>
        </div>

        {/* Mobile Menu Button */}
        <div className="md:hidden flex items-center gap-2">
          <ThemeToggle />
          <button
            className="text-foreground"
            onClick={() => setMobileOpen(!mobileOpen)}
          >
            {mobileOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>
      </nav>

      {/* Mobile Nav */}
      {mobileOpen && (
        <div className="md:hidden glass-panel border-t border-border/20 animate-fade-in">
          <div className="container mx-auto px-4 py-4 flex flex-col gap-4">
            {navLinks.map((link) => (
              <Link
                key={link.href}
                to={link.href}
                onClick={() => setMobileOpen(false)}
                className={cn(
                  "text-foreground/70 hover:text-foreground font-medium py-2 transition-colors",
                  location.pathname === link.href && "text-primary"
                )}
              >
                {link.label}
              </Link>
            ))}
            <Button variant="gold" className="mt-2">
              ابدأ الآن
            </Button>
          </div>
        </div>
      )}
    </header>
  );
};

export default Navbar;
