// web-angular/src/app/components/product-carousel/product-carousel.component.ts
import { Component, Input, ViewChild, ElementRef, signal, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, ChevronLeft, ChevronRight } from 'lucide-angular';
import { Product } from '@/app/data/brands';
import { ProductCardComponent } from '../product-card/product-card.component';

@Component({
    selector: 'app-product-carousel',
    standalone: true,
    imports: [CommonModule, LucideAngularModule, ProductCardComponent],
    templateUrl: './product-carousel.component.html',
})
export class ProductCarouselComponent implements AfterViewInit {
    @Input({ required: true }) products!: Product[];
    @Input({ required: true }) brandColor!: string;

    @ViewChild('scrollContainer') scrollContainer!: ElementRef<HTMLDivElement>;

    canScrollLeft = signal(false);
    canScrollRight = signal(false);

    readonly ChevronLeft = ChevronLeft;
    readonly ChevronRight = ChevronRight;

    ngAfterViewInit() {
        // Initial check
        setTimeout(() => {
            this.checkScroll();
            // Set initial state based on length if view init checking isn't enough
            if (this.products.length > 2) {
                // Force check
                this.checkScroll();
            }
        });
    }

    checkScroll() {
        if (this.scrollContainer) {
            const el = this.scrollContainer.nativeElement;
            const { scrollLeft, scrollWidth, clientWidth } = el;
            // RTL: scrollLeft is negative usually in some browsers, or positive in others depending on implementation.
            // Chrome/Edge: RTL scrollLeft is usually negative or 0 to -max.
            // Actually standardizing on checking offset.
            // Let's assume standard behavior or try to be robust.
            // React code: scrollLeft < -10 (implies negative range).

            // We will rely on element properties.
            // Simplest check:
            this.canScrollLeft.set(Math.abs(scrollLeft) > 10); // Scrolled away from start (right side in RTL)
            this.canScrollRight.set(Math.abs(scrollLeft) < scrollWidth - clientWidth - 10); // Not yet at end (left side in RTL)

            // Wait, in RTL:
            // Start is rightmost (scrollLeft 0 or max depending on browser).
            // React code: 
            // setCanScrollLeft(scrollLeft < -10); // Means we moved LEFT from 0? 0 is start?
            // If 0 is start (Right), and we scroll Left, scrollLeft becomes negative?
            // Yes, modern Chrome uses negative values for RTL scrolling left.
        }
    }

    scroll(direction: 'left' | 'right') {
        if (this.scrollContainer) {
            const scrollAmount = 200;
            // RTL: left moves more negative, right moves towards 0.
            // React: left -> +200, right -> -200?
            // React code: left: direction === "left" ? scrollAmount : -scrollAmount
            // If we are at 0 (Right), creating positive scrollLeft usually does nothing in RTL negative mode.
            // We want to scroll LEFT (visually). That means decreasing scrollLeft (more negative).
            // So 'left' direction should ADD negative scroll.
            // React code says: left -> positive scrollAmount? That would mean scrolling RIGHT visually if start is 0?
            // Wait, "scroll(left)" usually means "click left arrow to go left".
            // Visually moving content to right? No, viewport moves left.
            // Let's stick to the React logic: 
            // direction === "left" ? scrollAmount : -scrollAmount.

            this.scrollContainer.nativeElement.scrollBy({
                left: direction === 'left' ? scrollAmount : -scrollAmount,
                behavior: 'smooth',
            });
            setTimeout(() => this.checkScroll(), 300);
        }
    }
}

@if (products.length <= 2) { <div class="grid grid-cols-2 gap-3">
    @for (product of products; track product.id) {
    <app-product-card [product]="product" [brandColor]="brandColor"></app-product-card>
    }
    </div>
    } @else {
    <div class="relative group/carousel">
        <!-- Navigation Arrows -->
        @if (canScrollRight()) {
        <button (click)="scroll('right')"
            class="absolute right-0 top-1/2 -translate-y-1/2 translate-x-3 z-10 w-8 h-8 rounded-full bg-background/90 backdrop-blur border border-border/50 flex items-center justify-center text-foreground opacity-0 group-hover/carousel:opacity-100 transition-opacity shadow-lg hover:scale-110"
            [style.color]="'hsl(' + brandColor + ')'">
            <lucide-icon [name]="ChevronRight" class="w-4 h-4"></lucide-icon>
        </button>
        }

        @if (canScrollLeft()) {
        <button (click)="scroll('left')"
            class="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-3 z-10 w-8 h-8 rounded-full bg-background/90 backdrop-blur border border-border/50 flex items-center justify-center text-foreground opacity-0 group-hover/carousel:opacity-100 transition-opacity shadow-lg hover:scale-110"
            [style.color]="'hsl(' + brandColor + ')'">
            <lucide-icon [name]="ChevronLeft" class="w-4 h-4"></lucide-icon>
        </button>
        }

        <!-- Products Container -->
        <div #scrollContainer (scroll)="checkScroll()"
            class="flex gap-3 overflow-x-auto scrollbar-hide pb-2 snap-x snap-mandatory"
            style="scrollbar-width: none; -ms-overflow-style: none;" dir="rtl">
            @for (product of products; track product.id) {
            <div class="flex-shrink-0 w-[140px] snap-start">
                <app-product-card [product]="product" [brandColor]="brandColor"></app-product-card>
            </div>
            }
        </div>

        <!-- Scroll Indicator -->
        <div class="flex justify-center gap-1 mt-2">
            @for (item of products.slice(0, 5); track $index) {
            <div class="w-1.5 h-1.5 rounded-full bg-muted-foreground/30"></div>
            }
        </div>
    </div>
    }

// web/src/components/ProductCarousel.tsx
import { useState, useRef } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Product } from "@/data/brands";
import ProductCard from "./ProductCard";

interface ProductCarouselProps {
  products: Product[];
  brandColor: string;
}

const ProductCarousel = ({ products, brandColor }: ProductCarouselProps) => {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(products.length > 2);
  const [canScrollRight, setCanScrollRight] = useState(false);

  const checkScroll = () => {
    if (scrollRef.current) {
      const { scrollLeft, scrollWidth, clientWidth } = scrollRef.current;
      // RTL: scrollLeft is negative
      setCanScrollLeft(scrollLeft < -10);
      setCanScrollRight(Math.abs(scrollLeft) < scrollWidth - clientWidth - 10);
    }
  };

  const scroll = (direction: "left" | "right") => {
    if (scrollRef.current) {
      const scrollAmount = 200;
      // RTL: directions are reversed
      scrollRef.current.scrollBy({
        left: direction === "left" ? scrollAmount : -scrollAmount,
        behavior: "smooth",
      });
      setTimeout(checkScroll, 300);
    }
  };

  if (products.length <= 2) {
    return (
      <div className="grid grid-cols-2 gap-3">
        {products.map((product) => (
          <ProductCard key={product.id} product={product} brandColor={brandColor} />
        ))}
      </div>
    );
  }

  return (
    <div className="relative group/carousel">
      {/* Navigation Arrows - RTL adjusted */}
      {canScrollRight && (
        <button
          onClick={() => scroll("right")}
          className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-3 z-10 w-8 h-8 rounded-full bg-background/90 backdrop-blur border border-border/50 flex items-center justify-center text-foreground opacity-0 group-hover/carousel:opacity-100 transition-opacity shadow-lg hover:scale-110"
          style={{ color: `hsl(${brandColor})` }}
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      )}
      {canScrollLeft && (
        <button
          onClick={() => scroll("left")}
          className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-3 z-10 w-8 h-8 rounded-full bg-background/90 backdrop-blur border border-border/50 flex items-center justify-center text-foreground opacity-0 group-hover/carousel:opacity-100 transition-opacity shadow-lg hover:scale-110"
          style={{ color: `hsl(${brandColor})` }}
        >
          <ChevronLeft className="w-4 h-4" />
        </button>
      )}

      {/* Products Container */}
      <div
        ref={scrollRef}
        onScroll={checkScroll}
        className="flex gap-3 overflow-x-auto scrollbar-hide pb-2 snap-x snap-mandatory"
        style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
        dir="rtl"
      >
        {products.map((product) => (
          <div key={product.id} className="flex-shrink-0 w-[140px] snap-start">
            <ProductCard product={product} brandColor={brandColor} />
          </div>
        ))}
      </div>

      {/* Scroll Indicator */}
      <div className="flex justify-center gap-1 mt-2">
        {Array.from({ length: Math.min(products.length, 5) }).map((_, i) => (
          <div
            key={i}
            className="w-1.5 h-1.5 rounded-full bg-muted-foreground/30"
          />
        ))}
      </div>
    </div>
  );
};

export default ProductCarousel;
